on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          # Disable building for PyPy, 32bit
          CIBW_SKIP: pp* *-win32 *-manylinux_i686 *-musllinux*
          CIBW_BEFORE_TEST: pip install -r requirements_test.txt
          CIBW_TEST_COMMAND: pytest {project}/tests
