on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pip and development dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_develop.txt

      - name: Build package
        run: |
          python -m cython quadprog/quadprog.pyx
          python -m build --sdist

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist/quadprog*.tar.gz

  test:
    needs: build

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip and test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt

      - name: Download package
        run: |
          echo TODO download package

      - name: Install package
        run: |
          pip install dist/quadprog*.tar.gz

      - name: Run tests
        run: |
          pytest